
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 20;
  public static final int GLOB = 2;
  public static final int PLUS = 21;
  public static final int NEG = 16;
  public static final int RBRACE = 31;
  public static final int RPAREN = 29;
  public static final int OR = 19;
  public static final int SEMI = 27;
  public static final int LOCAL = 6;
  public static final int NOT = 17;
  public static final int RETURN_KW = 8;
  public static final int ASSIGN_OP = 26;
  public static final int LBRACE = 30;
  public static final int LPAREN = 28;
  public static final int GT = 25;
  public static final int ELSE_KW = 15;
  public static final int WHILE_KW = 11;
  public static final int STRING = 34;
  public static final int NUMBER = 33;
  public static final int MULT = 23;
  public static final int EOF = 0;
  public static final int FUNC = 4;
  public static final int MAIN = 5;
  public static final int DIV = 24;
  public static final int MINUS = 22;
  public static final int IF_KW = 14;
  public static final int PRINT = 10;
  public static final int error = 1;
  public static final int PROC = 3;
  public static final int EQ = 18;
  public static final int UNTIL = 13;
  public static final int HALT = 9;
  public static final int USER_DEFINED_NAME = 32;
  public static final int VAR = 7;
  public static final int DO_KW = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "GLOB",
  "PROC",
  "FUNC",
  "MAIN",
  "LOCAL",
  "VAR",
  "RETURN_KW",
  "HALT",
  "PRINT",
  "WHILE_KW",
  "DO_KW",
  "UNTIL",
  "IF_KW",
  "ELSE_KW",
  "NEG",
  "NOT",
  "EQ",
  "OR",
  "AND",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "GT",
  "ASSIGN_OP",
  "SEMI",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "USER_DEFINED_NAME",
  "NUMBER",
  "STRING"
  };
}

